export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children,users,revenue,notifications }) {
    return (
      <html lang="en">
        <body>
          <header>
            welcome to this Website
            </header>{children}</body>
            <div>{users}</div>
            <div>{revenue}</div>
            <div>{notifications}</div>
      </html>
    )
  }

//   agr ek complex page bnana hai toh aklg alg components import krne honge 
//   ya phir parallel routes bnane honge tki ye layout un sb page pe automatically cover kre 
// @ krkr define kro folder name 
  