import { props } from "./[id]/page"

props
export const metadata = {
  title: `${props.productid}`,
  description: 'Generated by Next.js',
}
// here we will be needing a dynamic data for each product 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <h2>Featured Product</h2>
      {children}</body>
    </html>
  )
}


// handling eroor in layout 
// layout aur error same jgh ho toh phir layout ka error wo error.js handle nhi krega
// error.js ko uske parent folder mer dalna hoga for this 